sudo: true
language: java
jdk:
- oraclejdk8


notifications:
  slack: dyti234:6KAy6KgKN7R8TJbsIxsgukNF
  email:
  - davidyannick@gmail.com

services:
  - docker
  - mongodb

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
